# -*- coding: utf-8 -*-
"""Basic_ChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17_ZHHeRh5o0-uGivAVPLRaCXOdkYLhYU
"""

import nltk
import random
import string
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize


nltk.download('punkt')
nltk.download('wordnet')
# predefined set of responses
RESPONSES = {
    "hello": "Hi there! How can I assist you today?",
    "how are you": "I'm just a bot, but I'm doing well! How about you?",
    "what is your name": "I'm ChatBot, your virtual assistant.",
    "bye": "Goodbye! Have a great day!",
    "what can you do": "I can chat with you, answer simple questions, and assist with various tasks. How can I help?",
    "who created you": "I was created by a team of developers who enjoy building chatbots!",
    "what is the time": "I don't have a watch, but your device should tell you the time.",
    "what is your favorite color": "I don't have eyes to see, but I'd imagine I would like blue. What about you?",
    "tell me a joke": "Sure! Why don't scientists trust atoms? Because they make up everything!",
    "what is your purpose": "I'm here to assist you with information and have a friendly chat!",
    "how old are you": "I don't age like humans, but I was born the day my code was written.",
    "do you like humans": "I think humans are fascinating! You're creative, complex, and fun to talk to.",
    "where do you live": "I live in the cloud, always ready to chat with you from anywhere.",
    "what is the weather": "I can't check the weather directly, but you could use your favorite weather app for that!",
    "what do you like to do": "I like helping people out and having fun conversations. What do you like doing?",
    "can you help me": "Of course! What do you need assistance with today?",
    "tell me a fun fact": "Did you know? The Eiffel Tower can be 15 cm taller during the summer due to the expansion of iron in the heat.",
    "are you real": "I'm real in the sense that I'm here talking to you! But I'm made of code, not flesh and bones.",
    "can you learn": "I don't learn like humans do, but I can be programmed to improve and adapt to new tasks.",
    "what do you eat": "I don't eat, but I do process data. That's what keeps me going!",
}


def tokenize(text):
    """Tokenize input text into words."""
    return word_tokenize(text.lower())

def get_greeting(text):
    """Check for greetings and return a friendly response."""
    greetings = ["hi", "hello", "hey","hy","greetings", "sup", "what's up"]
    for word in tokenize(text):
        if word in greetings:
            return "Hello! How can I help you today?"
    return None

def get_synonym(word):
    """Find a synonym for a word using WordNet."""
    synonyms = wordnet.synsets(word)
    if synonyms:
        return synonyms[0].lemmas()[0].name()
    return None

def respond_to_user(input_text):
    """Respond to the user input."""
    # Normalize and tokenize the user input
    user_input = input_text.lower()
    tokens = tokenize(user_input)

    # Check if input matches a predefined response directly
    for key in RESPONSES:
        if key in user_input:
            return RESPONSES[key]

    # Check for greetings
    greeting = get_greeting(user_input)
    if greeting:
        return greeting

    # Synonym matching
    for token in tokens:
        synonym = get_synonym(token)
        if synonym:
            for key in RESPONSES:
                if synonym in key:
                    return RESPONSES[key]

    # Handle unrecognized input
    return "I'm not sure how to respond to that. Can you rephrase?"



def chatbot():
    """Main chatbot function to interact with the user."""
    print("ChatBot: Hello! Type 'bye' to exit the chat.")

    while True:
        user_input = input("You: ")
        if user_input.lower() == "bye":
            print("ChatBot: Goodbye! Have a great day!")
            break

        response = respond_to_user(user_input)
        print(f"ChatBot: {response}")

if __name__ == "__main__":
    chatbot()

